# Generated by Django 4.2.7 on 2026-07-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chattea_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chats',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='chats',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='chats',
            name='mode',
            field=models.CharField(default='quotes', max_length=30),
        ),
        migrations.AddField(
            model_name='chats',
            name='sender',
            field=models.CharField(default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='chats',
            name='messages',
            field=models.CharField(max_length=5000),
        ),
    ]
